### PR TITLE
Fix IOError opening aws-in-us.json

### PR DESCRIPTION
**Pull request by brunns**
I'm getting:

    IOError: [Errno 2] No such file or directory: u'/root/AWSScout2/rules/data/ip-ranges/aws-in-us.json' 

This change seems to fix it for me.

### CODE REVIEW

**Comment by brunns** [comment]
Hi, @l01cd3v, I wonder if you can help with this? The build is [failing](https://travis-ci.org/nccgroup/Scout2/builds/313163819) with `Error: could not find AWS credentials. Use the --help option for more information.`, while running `nosetests --with-coverage --nocapture tests/test-scout2.py`. How should Travis CI get hold of AWS creds?

**Comment by l01cd3v** [comment]
Hi,

Thanks for the PR ! I need to test it locally because I _think_ that there may be a bug as I think the file should look like it originally did, so I want to double check what \_IP_RANGES\_FROM\_LOCAL\_FILE\_ does.

As far a the PR failure, I am not sure how to configure Travis such that it would work, as I set up the credentials to be secrets; I'm assuming this is a security mechanism to prevent PRs from extracting secret environment variables by adding some custom code that reads & prints them... maybe I should consider making these creds non secret as it's only list/describe in a test account...

It may  take me a little while to have a look at this one as I'm busy w/ work.

**Comment by brunns** [comment]
Thanks for coming back to me. I'm not sure that this PR works agains latest trunk, though, so I may ditch it and try again.

**Comment by l01cd3v** [comment]
Sounsd good, I'm going to open an issue to make sure I write some unit tests for the " _IP_RANGES_FROM_LOCAL_FILE_" if they're not in there yet.

**Comment by j4v** [comment]
The issue here is that the `AWSScout2/rules/data/ip-ranges/aws-in-us.json` path variable gets passed to opinel's `read_ip_ranges()` method in `AWSScout2/rules/rule.py` L107, which then call's opinel's `load_data()` which does the following:
```
            src_dir = os.getcwd()
            src_file = os.path.join(src_dir, data_file)
```
`os.getcwd()` will take the folder from which Scout2 is being executed from (in this case `/root/`), and concatenate the `AWSScout2/rules/data/ip-ranges/aws-in-us.json`  path, resulting in an invalid full path.
This is the same as issue #232 .

**Pull request closed without merging**
