### PR TITLE
Test CIS rules do not crash

### PR DESCRIPTION
**Pull request by brunns**

### CODE REVIEW

**Comment by l01cd3v** [comment]
Thanks ! I'd like this run to be local `--local` to avoid re-fetching the entire data set and keep the tests as fast as possible. Other than that nothing against more testing :)

**Comment by brunns** [comment]
Trouble is, [Nose doesn't guarantee in which order the tests are run](https://github.com/nose-devs/nose/issues/110). That's by design, because unit tests should be independent. 

This test isn't a unit test, of course, so I'll see if there's something clever I can do with [`setUpClass`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUpClass). (I don't want to put both runs into a single test method because it would be handy to be able to run just the one sometimes.)

**Comment by brunns** [comment]
Yup, there's a setUpClass now, so all but the 1st run will use `--local`.

**Comment by brunns** [comment]
Note that the existing `setup` method runs once per test, rather than just once. Is that intentional? If not, I can fix that too.

**Comment by l01cd3v** [comment]
Thanks ! I wasn't aware of the setUpClass method.

**Comment by l01cd3v** [comment]
I'll move the code from the setup method in there then !

**Pull request merged**
